apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
      - name: prediction-api
        image: prediction-api:latest
        ports:
        - containerPort: 5000
